name: CD - Deploy to EC2

on:
  workflow_call:
    secrets:
      EC2_HOST:
        required: true
      EC2_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Call Composite Action
        uses: ./.github/actions   # 👈 LOCAL COMPOSITE ACTION

        with:
          ec2-host: ${{ secrets.EC2_HOST }}
          ec2-user: ec2-user

        env:
          EC2_KEY: ${{ secrets.EC2_KEY }}

