name: Main CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  deploy:
    needs: ci
    uses: ./.github/workflows/deploy.yml

    with:
      ec2-user: ec2-user

    secrets:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_SSH_KEY: ${{ secrets.EC2_KEY }}
